services:
  db:
    image: postgres:18-alpine
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # Change the end of this line from /data to just /postgresql
      - postgres_data:/var/lib/postgresql

  cron: 
      build: .
      container_name: supercronic_worker
      restart: always
      depends_on:
        - db
      command: supercronic /app/crontab
      environment:
        - PYTHONPATH=/app
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
      volumes:
        - .:/app

volumes:
  postgres_data: